version: 3

dotenv: ['.env']
env:
  AUCTIONS_MIGRATIONS_DIR: store/auctions/migrations
tasks:

  seed-auctions: go run scripts/seed_auctions.go
  postgres-up: docker compose  -f  ./infra/config/postgres/docker-compose.yaml up -d
  postgres-down: docker compose  -f  ./infra/config/postgres/docker-compose.yaml down

  run: go run main.go

  migrate-new:
    desc: task migrate -- [migration_pair_name]
    cmds:
      - migrate create -seq -ext=.sql -dir=$AUCTIONS_MIGRATIONS_DIR {{.CLI_ARGS}}
  migrate-up:
    desc: execute migrations
    cmds:
      - migrate -path=$AUCTIONS_MIGRATIONS_DIR -database=$POSTGRESQL_URL up
  migrate-down:
    desc: down all migrations
    cmds:
      - migrate -path=$AUCTIONS_MIGRATIONS_DIR  -database=$POSTGRESQL_URL down
  migrate-goto:
    desc: migrate to a specific version
    cmds:
      - migrate -path=$AUCTIONS_MIGRATIONS_DIR  -database=$POSTGRESQL_URL  goto {{.CLI_ARGS}}
  migrate-force:
    desc: used for fixing errors in SQL migrations
    cmds:
      - migrate -path=$AUCTIONS_MIGRATIONS_DIR  -database=$POSTGRESQL_URL force {{.CLI_ARGS}}

  migrate-version:
    desc: show current version
    cmds:
      - migrate -path=$AUCTIONS_MIGRATIONS_DIR  -database=$POSTGRESQL_URL version